version: 2 # use CircleCI 2.0
jobs: # a collection of steps
  build: # runs not using Workflows must have a `build` job as entry point
    parallelism: 1
    docker: # run the steps with Docker
      - image: cimg/ruby:3.0.1-node # ...with this image as the primary container; this is where all `steps` will run
        environment: # environment variables for primary container
          BUNDLE_JOBS: 3
          BUNDLE_RETRY: 3
          BUNDLE_PATH: vendor/bundle
          PGHOST: 127.0.0.1
          PGUSER: excide
          RAILS_ENV: test
          NODE_ENV: test
      - image: circleci/postgres:13.1 # database image
        environment: # environment variables for database
          POSTGRES_USER: excide
          POSTGRES_DB: excide_test
          POSTGRES_PASSWORD: password
    steps: # a collection of executable commands
      - checkout # special step to check out source code to working directory

      # Which version of bundler?
      - run:
          name: Which bundler?
          command: bundle -v

      # Restore bundle cache
      # Read about caching dependencies: https://circleci.com/docs/2.0/caching/
      - restore_cache:
          keys:
            - excide-{{ checksum "Gemfile.lock" }}
            - excide-

      - run: # Install Ruby dependencies
          name: Bundle Install
          command: bundle check || bundle install

      # Store bundle cache for Ruby dependencies
      - save_cache:
          key: excide-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle
      - run:
          name: Wait for DB
          command: dockerize -wait tcp://localhost:5432 -timeout 1m

      - run:
          name: Copy database configuration
          command: cp config/database.yml.example config/database.yml

      - run:
          name: Database setup
          command: bin/rails db:schema:load --trace

      - restore_cache:
            keys:
              - yarn-{{ checksum "yarn.lock" }}

      - run:
          name: Yarn install
          command: yarn install --cache-folder ~/.cache/yarn

        # save yarn cache
      - save_cache:
          key: yarn-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn

      - restore_cache:
          keys:
            - webpack-{{ .Revision }}

      - run:
          name: Compile webpacker assets
          command: bundle exec rake webpacker:compile
          no_output_timeout: 35m

      - save_cache:
          key: webpack-{{ .Revision }}
          paths:
            - /home/circleci/project/public/packs-test/

      - run:
          name: Run rspec in parallel
          command: |
            bundle exec rspec --profile 10 \
                              --format RspecJunitFormatter \
                              --out test_results/rspec.xml \
                              --format progress \
                              $(circleci tests glob "spec/**/*_spec.rb" | circleci tests split --split-by=timings)

      # Save test results for timing analysis
      - store_test_results: # Upload test results for display in Test Summary: https://circleci.com/docs/2.0/collect-test-data/
          path: test_results
      # See https://circleci.com/docs/2.0/deployment-integrations/ for example deploy configs
