# This file was generated by the docusign_rest:generate_config rake task.
# You can run 'rake docusign_rest:generate_config' as many times as you need
# to replace the content of this file with a new config.

require 'docusign_rest'

DocusignRest.configure do |config|
  config.username       = 'admin@excide.co'
  config.password       = 'fE3}yzPWkRLDE)e4iSz3L2mr'
  config.integrator_key = '75b0deb6-b5fe-4516-9150-eeaac68b0130'
  config.account_id     = '3060480'
  #config.endpoint       = 'https://www.docusign.net/restapi'
  #config.api_version    = 'v2'
end

